# Generated by Django 3.0.4 on 2020-03-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('date_started', models.DateField(verbose_name='start_project')),
                ('date_finished', models.DateField(verbose_name='end_project', blank=True)),
            ],
        ),
    ]
